server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uywojh/docs-config-repo.git
          search-paths: didispace
          username: 664507439@qq.com
          password: wu15180180820
          force-pull: true
        health:
          repositories:
            check:
              #应用名
              name: docs-config-repo
              #分支名
              label: master
              #环境名
              profile: default
        prefix:
application:
    name: config-server
rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/