spring:
  cloud:
    config:
      label: master
      discovery:
        enabled: true
        service-id: config-server
      profile: dev
      fail-fast: true
    bus:
      trace:
        enabled: true  #开启消息跟踪
application:
    name: config-client
rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 123456
server:
  port: 8887
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/